# Generated by Django 4.2.2 on 2023-08-20 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waterGIS", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
