# Generated by Django 4.2.2 on 2023-08-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waterGIS", "0003_remove_user_followers_delete_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_premium_user",
            field=models.CharField(
                choices=[
                    ("NO", "Not a premium user"),
                    ("PENDING", "Pending approval for premium access"),
                    ("YES", "Is a premium user"),
                ],
                default="NO",
                max_length=20,
            ),
        ),
    ]
